# Generated by Django 3.0.6 on 2020-06-05 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('brief', models.CharField(max_length=2500)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blog_Img')),
                ('slug', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 16, 58, 11, 866575))),
            ],
        ),
    ]
