# Generated by Django 3.0.6 on 2020-06-07 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_crousal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='crousal',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='crousal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
